version: '3'
services:
  users:
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run start && npm run typeorm:dev migration:run && npm run start:dev"
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - users_network
    restart: always

  postgres:
    container_name: postgres
    image: "postgres:9.6.1"
    ports:
      - ${DB_PORT_EXT}:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "admin"
    volumes:
      - ./data_volumes/postgres:/var/lib/postgresql/data
    networks:
      - users_network
    restart: always

networks:
  users_network:
